---
# See the documentation for more information:
# https://packit.dev/docs/configuration/

downstream_package_name: aardvark-dns
upstream_tag_template: v{version}

# These files get synced from upstream to downstream (Fedora / CentOS Stream) on every
# propose-downstream job. This is done so tests maintained upstream can be run
# downstream in Zuul CI and Bodhi.
# Ref: https://packit.dev/docs/configuration#files_to_sync
files_to_sync:
  - src: rpm/gating.yaml
    dest: gating.yaml
    delete: true
  - src: plans/
    dest: plans/
    delete: true
    mkpath: true
  - src: test/tmt
    dest: test/tmt
    delete: true
    mkpath: true
  - src: .fmf/
    dest: .fmf/
    delete: true
  - .packit.yaml

packages:
  aardvark-dns-fedora:
    pkg_tool: fedpkg
    specfile_path: rpm/aardvark-dns.spec
  aardvark-dns-centos:
    pkg_tool: centpkg
    specfile_path: rpm/aardvark-dns.spec
  aardvark-dns-eln:
    specfile_path: rpm/aardvark-dns.spec

srpm_build_deps:
  - cargo
  - git-archive-all
  - make
  - openssl-devel

# https://packit.dev/docs/configuration/actions
# fix-spec-file only operates on copr builds and doesn't affect official distro builds
actions:
  fix-spec-file: "bash .packit-copr-rpm.sh"

jobs:
  - job: copr_build
    trigger: pull_request
    packages: [aardvark-dns-fedora]
    notifications: &copr_build_failure_notification
      failure_comment:
        message: "Ephemeral COPR build failed. @containers/packit-build please check."
    targets: &fedora_copr_targets
      - fedora-all-x86_64
      - fedora-all-aarch64
    enable_net: true
    osh_diff_scan_after_copr_build: false

  - job: copr_build
    trigger: pull_request
    packages: [aardvark-dns-eln]
    notifications: *copr_build_failure_notification
    targets:
      fedora-eln-x86_64:
        additional_repos:
          - "https://kojipkgs.fedoraproject.org/repos/eln-build/latest/x86_64/"
      fedora-eln-aarch64:
        additional_repos:
          - "https://kojipkgs.fedoraproject.org/repos/eln-build/latest/aarch64/"
    enable_net: true

  - job: copr_build
    trigger: pull_request
    packages: [aardvark-dns-centos]
    notifications: *copr_build_failure_notification
    targets: &centos_copr_targets
      - centos-stream-9-x86_64
      - centos-stream-9-aarch64
      - centos-stream-10-x86_64
      - centos-stream-10-aarch64
    enable_net: true

  # Run on commit to main branch
  - job: copr_build
    trigger: commit
    packages: [aardvark-dns-fedora]
    notifications:
      failure_comment:
        message: "podman-next COPR build failed. @containers/packit-build please check."
    branch: main
    owner: rhcontainerbot
    project: podman-next
    enable_net: true

  # Tests on Fedora
  - job: tests
    trigger: pull_request
    packages: [aardvark-dns-fedora]
    notifications: &test_failure_notification
      failure_comment:
        message: "Tests failed. @containers/packit-build please check."
    targets: *fedora_copr_targets
    tf_extra_params:
      environments:
        - artifacts:
          - type: repository-file
            id: https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/repo/fedora-$releasever/rhcontainerbot-podman-next-fedora-$releasever.repo

  # Tests on CentOS Stream
  - job: tests
    trigger: pull_request
    packages: [aardvark-dns-centos]
    notifications: *test_failure_notification
    targets: *centos_copr_targets
    tf_extra_params:
      environments:
        - artifacts:
          - type: repository-file
            id: https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/repo/centos-stream-$releasever/rhcontainerbot-podman-next-centos-stream-$releasever.repo

  # Sync to Fedora
  - job: propose_downstream
    trigger: release
    packages: [aardvark-dns-fedora]
    update_release: false
    dist_git_branches: &fedora_targets
      - fedora-all

  # Sync to CentOS Stream
  - job: propose_downstream
    trigger: release
    packages: [aardvark-dns-centos]
    update_release: false
    dist_git_branches:
      - c10s
      - c9s

  - job: koji_build
    trigger: commit
    packages: [aardvark-dns-fedora]
    sidetag_group: netavark-releases
    dependents:
      - netavark
    dist_git_branches: *fedora_targets
