---
# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: rpm/aardvark-dns.spec
upstream_tag_template: v{version}

srpm_build_deps:
  - cargo
  - make
  - openssl-devel

jobs:
  - job: copr_build
    trigger: pull_request
    notifications:
      failure_comment:
        message: "Ephemeral COPR build failed. @containers/packit-build please check."
    targets:
      fedora-all-x86_64: {}
      fedora-all-aarch64: {}
      fedora-eln-x86_64:
        additional_repos:
          - "https://kojipkgs.fedoraproject.org/repos/eln-build/latest/x86_64/"
      fedora-eln-aarch64:
        additional_repos:
          - "https://kojipkgs.fedoraproject.org/repos/eln-build/latest/aarch64/"
      epel-8-x86_64: {}
      epel-8-aarch64: {}
      epel-9-x86_64: {}
      epel-9-aarch64: {}
    additional_repos:
      - "copr://rhcontainerbot/podman-next"
    enable_net: true

  # Jobs that run on internal testing farm are not run automatically for
  # external contributors. Having a separate build task for consumption by
  # internal testing farm tasks decouples the internal testing farm tasks from
  # the non-internal ones so that non-internal tasks get run automatically.
  - job: copr_build
    trigger: pull_request
    notifications:
      failure_comment:
        message: "Ephemeral COPR build failed. @containers/packit-build please check."
    targets:
      - epel-8-x86_64
      - epel-8-aarch64
      - epel-9-x86_64
      - epel-9-aarch64
    additional_repos:
      - "copr://rhcontainerbot/podman-next"
    enable_net: true
    identifier: integration_test_internal

  # Run on commit to main branch
  - job: copr_build
    trigger: commit
    notifications:
      failure_comment:
        message: "podman-next COPR build failed. @containers/packit-build please check."
    branch: main
    owner: rhcontainerbot
    project: podman-next
    enable_net: true

  # Validate test
  - job: tests
    trigger: pull_request
    skip_build: true
    targets:
      # Only need to test on one target
      - fedora-latest-stable-x86_64
    identifier: validate_test
    tmt_plan: "/plans/validate_test"

  # Unit tests
  - job: tests
    trigger: pull_request
    skip_build: true
    targets: &pr_test_targets
      - fedora-all-x86_64
      - fedora-all-aarch64
      - epel-8-x86_64
      - epel-8-aarch64
      - epel-9-x86_64
      - epel-9-aarch64
    identifier: unit_test
    tmt_plan: "/plans/unit_test"

  # Integration tests
  - job: tests
    trigger: pull_request
    targets: *pr_test_targets
    identifier: integration_test
    tmt_plan: "/plans/integration_test"

  # Unit tests on RHEL
  - job: tests
    trigger: pull_request
    skip_build: true
    use_internal_tf: true
    notifications:
      failure_comment:
        message: "podman e2e tests failed on RHEL. @containers/packit-build please check."
    targets: &pr_test_targets_rhel
      epel-8-aarch64:
        distros: [RHEL-8.9.0-Nightly,RHEL-8.10.0-Nightly]
      epel-8-x86_64:
        distros: [RHEL-8.9.0-Nightly,RHEL-8.10.0-Nightly]
      epel-9-aarch64:
        distros: [RHEL-9.3.0-Nightly,RHEL-9.4.0-Nightly]
      epel-9-x86_64:
        distros: [RHEL-9.3.0-Nightly,RHEL-9.4.0-Nightly]
    identifier: unit_test_internal
    tmt_plan: "/plans/unit_test"

  # Integration tests on RHEL
  - job: tests
    trigger: pull_request
    use_internal_tf: true
    notifications:
      failure_comment:
        message: "podman system tests failed on RHEL. @containers/packit-build please check."
    targets: *pr_test_targets_rhel
    identifier: integration_test_internal
    tmt_plan: "/plans/integration_test"

  - job: propose_downstream
    trigger: release
    update_release: false
    dist_git_branches:
      - fedora-all

  - job: koji_build
    trigger: commit
    dist_git_branches:
      - fedora-all

  - job: bodhi_update
    trigger: commit
    dist_git_branches:
      - fedora-branched # rawhide updates are created automatically
