---
# See the documentation for more information:
# https://packit.dev/docs/configuration/

downstream_package_name: aardvark-dns
upstream_tag_template: v{version}

# These files get synced from upstream to downstream (Fedora / CentOS Stream) on every
# propose-downstream job. This is done so tests maintained upstream can be run
# downstream in Zuul CI and Bodhi.
# Ref: https://packit.dev/docs/configuration#files_to_sync
files_to_sync:
  - src: rpm/gating.yaml
    dest: gating.yaml
    delete: true
  - src: plans/
    dest: plans/
    delete: true
  - src: .fmf/
    dest: .fmf/
    delete: true
  - .packit.yaml

packages:
  aardvark-dns-fedora:
    pkg_tool: fedpkg
    specfile_path: rpm/aardvark-dns.spec
  aardvark-dns-centos:
    pkg_tool: centpkg
    specfile_path: rpm/aardvark-dns.spec
  aardvark-dns-rhel:
    specfile_path: rpm/aardvark-dns.spec
  aardvark-dns-eln:
    specfile_path: rpm/aardvark-dns.spec

srpm_build_deps:
  - cargo
  - make
  - openssl-devel

jobs:
  - job: copr_build
    trigger: pull_request
    packages: [aardvark-dns-fedora]
    notifications: &copr_build_failure_notification
      failure_comment:
        message: "Ephemeral COPR build failed. @containers/packit-build please check."
    targets:
      - fedora-all-x86_64
      - fedora-all-aarch64
    enable_net: true

  - job: copr_build
    trigger: pull_request
    packages: [aardvark-dns-eln]
    notifications: *copr_build_failure_notification
    targets:
      fedora-eln-x86_64:
        additional_repos:
          - "https://kojipkgs.fedoraproject.org/repos/eln-build/latest/x86_64/"
      fedora-eln-aarch64:
        additional_repos:
          - "https://kojipkgs.fedoraproject.org/repos/eln-build/latest/aarch64/"
    enable_net: true

  - job: copr_build
    trigger: pull_request
    packages: [aardvark-dns-centos]
    notifications: *copr_build_failure_notification
    targets: &centos_copr_targets
      - centos-stream-9-x86_64
      - centos-stream-9-aarch64
      - centos-stream-10-x86_64
      - centos-stream-10-aarch64
    enable_net: true

  - job: copr_build
    trigger: pull_request
    packages: [aardvark-dns-rhel]
    notifications: *copr_build_failure_notification
    targets:
      - epel-9-x86_64
      - epel-9-aarch64
    enable_net: true

  # Run on commit to main branch
  - job: copr_build
    trigger: commit
    packages: [aardvark-dns-fedora]
    notifications:
      failure_comment:
        message: "podman-next COPR build failed. @containers/packit-build please check."
    branch: main
    owner: rhcontainerbot
    project: podman-next
    enable_net: true

  # Unit tests on Fedora
  - job: tests
    trigger: pull_request
    packages: [aardvark-dns-fedora]
    notifications: &test_failure_notification
      failure_comment:
        message: "Tests failed. @containers/packit-build please check."
    targets:
      - fedora-development-x86_64
      - fedora-development-aarch64
      - fedora-latest-x86_64
      - fedora-latest-aarch64
      - fedora-latest-stable-x86_64
      - fedora-latest-stable-aarch64
      - fedora-40-x86_64
      - fedora-40-aarch64

  # Unit tests on CentOS Stream
  - job: tests
    trigger: pull_request
    packages: [aardvark-dns-centos]
    notifications: *test_failure_notification
    targets: *centos_copr_targets

  # Unit tests on RHEL
  - job: tests
    trigger: pull_request
    packages: [aardvark-dns-rhel]
    notifications: *test_failure_notification
    use_internal_tf: true
    targets:
      epel-9-aarch64:
        distros: [RHEL-9-Nightly,RHEL-9.4.0-Nightly]
      epel-9-x86_64:
        distros: [RHEL-9-Nightly,RHEL-9.4.0-Nightly]
      # NOTE: Need to use centos-stream-10 until RHEL-10/EPEL-10 copr targets
      # are available
      # TODO: iptables kernel module is not available on rhel10.
      # Enable these after netavark default is switched to nftables.
      #centos-stream-10-aarch64:
      #  distros: [RHEL-10-Beta-Nightly]
      #centos-stream-10-x86_64:
      #  distros: [RHEL-10-Beta-Nightly]

  # Sync to Fedora
  - job: propose_downstream
    trigger: release
    packages: [aardvark-dns-fedora]
    update_release: false
    dist_git_branches: &fedora_targets
      - fedora-all

  # Sync to CentOS Stream
  - job: propose_downstream
    trigger: release
    packages: [aardvark-dns-centos]
    update_release: false
    dist_git_branches:
      - c10s
      - c9s

  - job: koji_build
    trigger: commit
    packages: [aardvark-dns-fedora]
    sidetag_group: netavark-releases
    dependents:
      - netavark
    dist_git_branches: *fedora_targets
